version: "3"
services:
  app:
    container_name: fastify-server
    restart: always
    build: ./
    env_file:
      - .env
    environment:
      - MONGODB_CONNECTION=mongodb://mongo:27017/contenu
      - SECRET_KEY=${SECRET_KEY}
      - JWT_EXPIRE_DAYS=${JWT_EXPIRE_DAYS}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
